name: Muba
on:
  workflow_dispatch:

jobs:
     execute-the-commad:
      runs-on: ubuntu-latest
      steps: 
         - name: Checkout
           uses: actions/checkout@v6.0.1
         - name: execute-the-command
           run: ls -a
   
  
  
